version: '3.8'
services:
  whatsapp-api:
    build: .
    ports:
      - "2000:2000"
    shm_size: '1gb'
    restart: always
    volumes:
      - whatsapp_session:/usr/src/app/.wwebjs_auth
      - whatsapp_cache:/usr/src/app/.wwebjs_cache
    environment:
      - PORT=2000

volumes:
  whatsapp_session:
  whatsapp_cache:
